name: task-management-system
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - sqlalchemy==2.0.23
    - alembic==1.12.1
    - psycopg2-binary==2.9.9
    - python-jose[cryptography]==3.3.0
    - passlib[bcrypt]==1.7.4
    - python-multipart==0.0.6
    - pydantic==2.5.0
    - pydantic-settings==2.1.0
    - python-dotenv==1.0.0
    - psutil==5.9.6
    - pynvml==11.5.0
    - schedule==1.2.0
    - pandas==2.1.3
    - pytest==7.4.3
    - pytest-asyncio==0.21.1
    - httpx==0.25.2
    - black==23.11.0
    - flake8==6.1.0
    - isort==5.12.0